# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Example.Company')),
            ],
        ),
    ]
