# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example', '0002_programer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='programer',
            name='languages',
            field=models.ManyToManyField(to='Example.Language'),
        ),
    ]
